### ISSUE TITLE
Release initial version on Packagist

### ISSUE THREAD

**Issue by ycombinator** [mikemccabe/json-patch-php#10]
Hi @mikemccabe,

It turns out that, in order for us to use your package in ours, [php-opencloud](https://packagist.org/packages/rackspace/php-opencloud), we need your package to have a release  (e.g `0.1.0`) on Packagist.

I see that your package already exists on Packagist over here: https://packagist.org/packages/mikemccabe/json-patch-php so that's a very good start.

If you agree to release an initial version, you will need to do the following:

1. [Login to Packagist](https://packagist.org/login/).
2. Once you are logged-in, click on your username in the top-right corner of the Packagist site, to the left of the "Logout" button. This will take you to your Packagist profile page.
3. Click the "Show API Token" link. This will show you your Packagist API token. Please copy this token to your clipboard. We will need this to publish your project from GitHub to Packagist. 
4. Open a new tab with https://github.com/mikemccabe/json-patch-php/settings/hooks as the URL.
5. Click the "Add Service" button. A dropdown should appear.
6. In the dropdown, type "Packagist" and hit enter. This will take you to the Packagist service configuration page. This service automatically pushes new releases from your GitHub repository to Packagist.
7. On the Packagist service configuration page, enter your Packagist username under the "User" field, your Packagist API token (copied to clipboard) under the "Token" field. You can leave the "Domain" field blank. Make sure the "Active" checkbox is checked.
8. Click the "Add Service" button to submit the form and add the Packagist service.
9. Next, you will need to publish the first release for your package on GitHub. To do this, visit https://github.com/mikemccabe/json-patch-php/releases/new.
10. Enter the release version you want in the "Tag version" field. I would suggest `0.1.0` as this is your very first release and there might be improvements yet to come. For the "Target" field, choose `master`. You can leave the "Release title" field blank; it will use the release version as the title. In the "Describe this release" field, enter a description such as, "Initial release".
11. Click the "Publish release" button at the bottom of the form to publish the release.
12. After a couple dozen seconds, check https://packagist.org/packages/mikemccabe/json-patch-php to make sure the new release has shown up.

Please note that, for future release, you need only do steps 9 through 12.

We hope you consider our request. Thank you!

**Comment by mikemccabe** [comment]
Done!  Thanks for the detailed steps.
